### ISSUE TITLE
Add source code to repository

### ISSUE THREAD

**Issue by autonomous1** [autonomous1/darkplacesrpi#11]

**Comment by superjamie** [comment]
Is there any update on this? DarkPlaces is under the GPL so source is a legal requirement if users ask for it, and users are asking for it. Lack of source is the reason this is not included in RetroPie. You don't have to tidy or curate the source or accept pull requests or anything, just push to git every now and then and get it out there.

**Comment by autonomous1** [comment]
It's only a legal requirement if you a selling something.

**Comment by superjamie** [comment]
That is not correct. To quite from the FSF's license preamble:

> For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.

https://www.gnu.org/licenses/gpl-2.0.html

https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by autonomous1** [comment]
Well that's my interpretation. IDK if they take it off github

**Comment by superjamie** [comment]
Your interpretation is clearly wrong and you're in violation of the license. It doesn't matter where the source or binaries are stored, what matters is that the license is adhered to. The reason this port is not included in RetroPie is because of your breach of the license terms. Please release the source, so that the license is adhered to, and so we can get your excellent work on this source port back into RetroPie.

**Comment by autonomous1** [comment]
Sorry all the source was lost in a burglary.

**Comment by superjamie** [comment]
Oh rubbish.

**Comment by joolswills** [comment]
@autonomous1  was asked for source years ago on the raspberrypi forum thread. I don't think he ever had any intention of releasing it.

**Comment by joolswills** [comment]
well 2 years ago anyway.
